module libc

fn memcpy(s1: rawptr, s2: rawptr, n: size_t) -> rawptr #foreign Libc #link_name "memcpy"
fn memmove(s1: rawptr, s2: rawptr, n: size_t) -> rawptr #foreign Libc #link_name "memmove"
fn strcpy(s1: ^char, s2: cstring) -> ^char #foreign Libc #link_name "strcpy"
fn strncpy(s1: ^char, s2: cstring, n: size_t) -> ^char #foreign Libc #link_name "strncpy"
fn strcat(s1: ^char, s2: cstring) -> ^char #foreign Libc #link_name "strcat"
fn strncat(s1: ^char, s2: cstring, n: size_t) -> ^char #foreign Libc #link_name "strncat"
fn memcmp(s1: rawptr, s2: rawptr, n: size_t) -> int #foreign Libc #link_name "memcmp"
fn strcmp(s1: cstring, s2: cstring) -> int #foreign Libc #link_name "strcmp"
fn strcoll(s1: cstring, s2: cstring) -> int #foreign Libc #link_name "strcoll"
fn strncmp(s1: cstring, s2: cstring, n: size_t) -> int #foreign Libc #link_name "strncmp"
fn strxfrm(s1: ^char, s2: cstring, n: size_t) -> size_t #foreign Libc #link_name "strxfrm"
fn memchr(s: rawptr, c: int, n: size_t) -> rawptr #foreign Libc #link_name "memchr"
fn strchr(s: cstring, c: int) -> ^char #foreign Libc #link_name "strchr"
fn strcspn(s1: cstring, s2: cstring) -> size_t #foreign Libc #link_name "strcspn"
fn strpbrk(s1: cstring, s2: cstring) -> ^char #foreign Libc #link_name "strpbrk"
fn strrchr(s: ^char, c: int) -> ^char #foreign Libc #link_name "strrchr"
fn strcpn(s1: cstring, s2: cstring) -> ^char #foreign Libc #link_name "strcpn"
fn strtok(s1: ^char, s2: cstring) -> ^char #foreign Libc #link_name "strtok"
fn strerror(errnum: int) -> cstring #foreign Libc #link_name "strerror"
fn strlen(s: cstring) -> size_t #foreign Libc #link_name "strlen"
fn memset(s: rawptr, c: int, n: size_t) -> rawptr #foreign Libc #link_name "memset"
